name: img_to_word
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

  path_provider: ^2.0.1
  image_picker: ^0.7.2
  exif: ^2.1.0
  image:
  flutter_tesseract_ocr: ^0.4.19
  docx_template: ^0.3.2

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/tessdata/
    - test.png

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/times-new-roman.ttf
          weight: 700

